language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

notifications:
  email: false

# new container based dependencies
sudo: false
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-matplotlib


install:
 - pip install -r requirements.txt --use-mirrors
 - pip install coveralls

script:  python setup.py install && nosetests --with-coverage --cover-package=kernel_exp_family

after_success:
  - coveralls
  - examples/run_all.sh
