# move to container based
sudo: false

# install necessary packages
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - python-matplotlib

language: python
python:
  - "2.7"

virtualenv:
  system_site_packages: true

notifications:
  email: false

before_install:
# - sudo apt-get install -qq python-numpy python-matplotlib gcc gfortran python-dev libblas-dev liblapack-dev cython libblas-dev libatlas-dev liblapack-dev python-coverage #python-scipy 

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
#install:
# - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:  export PYTHONPATH=$PYTHONPATH:~/kernel_exp_family && nosetests

